name: 'detect-newer-action'
description: 'Detects newer actions applied to your workflow.'
runs:
  using: node12
  main: dist/index.js
inputs:
  exclude-actions:
    description: "Exclude pattern filters of action's name with regex. Multiple pattern is available via separating with comma."
    required: false
  exclude-workflows:
    description: "Exclude pattern filters of workflow file name with regex. Multiple pattern is available via separating with comma."
    required: false
  output-file:
    description: "Output file name. Output file format is json. Empty or null then no output. Default empty"
    required: false
  token:
    description: "Github token that is able to call repo-list-tags api.(secrets.GITHUB_TOKEN)"
    required: true
outputs:
  diff:
    description: "Diff of action's version in json format."
branding:
  icon: package
  color: yellow
author: mike-neck
