on: [push]

jobs:
  testing:
    runs-on: ${{ matrix.run-os }}
    strategy:
      matrix:
        run-os: [ubuntu-latest, macos-latest, windows-latest]
    name: example test
    steps:
      - name: check out
        uses: actions/checkout@v2

      - name: example
        uses: ./
        with:
          excludes: '.+'
          output-file: 'test.json'
