on: [push]

jobs:
  testing:
    runs-on: ${{ matrix.run-os }}
    strategy:
      matrix:
        run-os: [ubuntu-latest, macos-latest, windows-latest]
    name: example test
    steps:
      - name: check out
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 12

      - name: setup project
        run: npm install

      - name: test
        run: npm test

      - name: build
        run: |
          npm run build
          npm run pack

      - name: example
        uses: ./
        with:
          exclude-actions: 'example'
          exclude-workflows: 'example.yml'
          output-file: 'test.json'
