on: [push]

jobs:
  testing:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    name: example test
    steps:
      - name: check out
        uses: actions/checkout@v2

      - name: example
        uses: ./
        with:
          excludes: '.+'
          output-file: 'test.json'
